component/Recipes/all-recipes.js, pages/[...slug]/index.js
Remaining recipes display when show more button. Counter decreases when laod more button is clicked
=> Mmapaseka Issue 21, 20,

database/index.js, pages/recipes/[recipeId].js
Added a single recipes page that will dynamically display the individual recipes in the app. Created a .env file in order to create variables to use when fetching the data. Currently only able to display the 20 recipes that are being fetched.
=> Single recipe page

Layout/layout.js, component/SideNav/SlidingNavbar.js, component/SideNav/sideNav.module.css, package-lock.json, package.json, pages/_app.js, tailwind.config.js
created a side navigation bar the expands on a click of an arrow
=> Created Nav bar

component/Error/ErrorMessage.js, component/Error/ErrorMessage.module.css, component/Recipes/Details/RecipeDetails.js
Added an error message component which is used in the recipeDetails component to conditionally display an error message if the recipe instructions are not loaded.
=> 7 display error on instructions load failure

component/Recipes/Preview/PreviewList.js
Created a component for the error display message on description
=> Created component for the error display

component/Recipes/Details/RecipeDetails.js
Change p tags to divs to remove the error of having a ul inside a p tag
=> Change p tags to divs to remove the error of having a ul inside a p tag

component/Recipes/Preview/PreviewList.js
we were getting the "Each child should have a key prop" in the previe list page.
now it is nomore
=> removed the key prop error

component/Recipes/Details/RecipeDetails.js, component/Recipes/FavouritesButton/FavouritesButton.js, component/Recipes/FavouritesButton/FavouritesButton.module.css
Added "Add to favourites" button in single recipe page.
=> 177 add favourite button to individual recipe page

component/home-page/HomeWithBackground.js, pages/favourites/index.js
Added link to the favourite recipes page. Created a favourites page.
=> 169 navigate to favourite recipes page

pages/favourites/index.js
Can display favourite recipes on the favourites page.
=> 170 display favourited recipes

component/filtering/filtering/filterbyIngredients.jsx, component/filtering/filtering/filterbyTags.jsx, database/getData/getFilteredResults.jsx, pages/[previews]/index.js, pages/api/filtering/filterOptions/filterIngredients.jsx, pages/api/filtering/filterOptions/filterTags.jsx, useContext/StateContext.jsx
Displayed the total number of the filtered results of the recipes.
=> Total_Filtered_Results

component/Recipes/Allergens/SingleAllergen.module.css, component/Recipes/Details/Info/info.jsx, next.config.js, pages/[previews]/[recipe].jsx
Can display allergens associated with the recipe.
=> 9 display of allergens in recipe description

component/Recipes/Preview/PreviewList.jsx
removed duplicate heading.
and white space
=> higlighting search input

component/Recipes/Allergens/SingleAllergen.jsx, component/Recipes/Allergens/SingleRecipeAllergens.jsx, component/Recipes/Details/Info/info.jsx, component/Recipes/Preview/PreviewList.jsx, component/Recipes/SingleRecipeTags/SingleRecipeTag.jsx, component/Recipes/SingleRecipeTags/SingleRecipeTags.jsx, component/handlerTime/timeRead.jsx, component/handlerTime/timeRead.module.css, next.config.js, package-lock.json, package.json
documented files in the handlertime folder in the component folder. Linted files in the linting scope
=> 334 documenting files in the handlertime folder in the component folder

component/handlerTime/timeRead.jsx
=> fixed time string

component/filtering/filtering/filterbyIngredients.jsx, component/filtering/filtering/filterbyInstructions.jsx, component/filtering/filtering/filterbyTags.jsx, component/filtering/searchAndFilterHero/searchAndFilterHero.jsx, component/filtering/searchCategories/categorySearch.jsx, pages/[previews]/index.jsx, styles/globals.css
Changed the image and added overlay
=> Documenting files in the 'recipes' folder

.eslintrc.json, component/Recipes/Allergens/SingleRecipeAllergens.jsx, component/Recipes/Details/Info/info.jsx, component/Recipes/SingleRecipeTags/SingleRecipeTag.jsx, component/Recipes/SingleRecipeTags/SingleRecipeTags.jsx, package-lock.json, package.json
Update eslintrc.json file and linted eslint scoped files.
=> Update eslintrc.json file

component/Recipes/Details/Info/info.jsx, pages/[previews]/[recipe].jsx
Can view ingredients with allergens on recipe details page. Removed "recipe" dependence from the useEffect that fetches the recipe.
=> Update display of allergens in recipe description 9

component/Recipes/SingleRecipeTags/SingleRecipeTag.jsx, component/Recipes/SingleRecipeTags/SingleRecipeTag.module.css, component/Recipes/SingleRecipeTags/SingleRecipeTags.module.css
turned tags button into spans and styled them
=> turned tags button into spans and styled them

component/filtering/searchCategories/categorySearch.jsx, pages/[previews]/index.jsx, useContext/StateContext.jsx
=> Url and issue206

pages/[previews]/index.jsx
Display an alert message if changing the number of instruction filters results in no recipes returned.
=> 216 no recipes have the specified number of steps

component/Recipes/SingleRecipeTags/SingleRecipeTag.jsx, component/Recipes/SingleRecipeTags/SingleRecipeTags.jsx, component/Recipes/SingleRecipeTags/SingleRecipeTags.module.css
Refactored, documented and linted the files in component/recipes/singleRecipeTags folder.
=> 426 refactoring and documenting componentrecipessinglerecipetags

component/editInstructions/editInstructions.jsx, component/editInstructions/editandAddInstruction.jsx, pages/[previews]/index.jsx
-Added title
-Made a default sorting option
=> 512 including label or heading to explain the recipe editing functionality

database/getData/getRecipesData.jsx
Linting of the getRecipesData file
=> 403 format all recipe titles

component/editInstructions/editandAddInstruction.jsx
Documentation of editAndAddInstructions file
=> Documentation

component/ui/loadingSkeleton.js/loading.jsx
=> 339 documenting files in the UI folder in the component folder
